# Generated by Django 2.1.4 on 2019-02-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddCollegeNewsModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('enternews', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AdminModel',
            fields=[
                ('username', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ArticleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articleid', models.IntegerField()),
                ('category', models.CharField(max_length=50)),
                ('tag', models.CharField(max_length=100)),
                ('article', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ModeratorModel',
            fields=[
                ('category', models.CharField(choices=[('sports', 'SPORTS'), ('nature', 'NATURE'), ('ourcollege', 'OURCOLLEGE'), ('technology', 'TECHNOLOGY')], max_length=100)),
                ('moderator_name', models.CharField(max_length=100)),
                ('userid', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=100)),
                ('mobile_num', models.IntegerField()),
                ('email_id', models.EmailField(max_length=200)),
            ],
        ),
    ]
