# Generated by Django 2.1.4 on 2019-02-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='article',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='moderatormodel',
            name='userid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
