# Generated by Django 2.1.4 on 2019-02-01 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_auto_20190201_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlemodel',
            name='article',
            field=models.TextField(),
        ),
    ]
