# Generated by Django 2.1.4 on 2019-02-02 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20190201_1917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articlemodel',
            name='id',
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='articleid',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='articlemodel',
            name='category',
            field=models.CharField(choices=[('sports', 'SPORTS'), ('nature', 'NATURE'), ('ourcollege', 'OURCOLLEGE'), ('technology', 'TECHNOLOGY')], max_length=50),
        ),
    ]
