# Generated by Django 2.1.4 on 2019-02-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_membermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membermodel',
            name='member_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='membermodel',
            name='mobile_num',
            field=models.IntegerField(),
        ),
    ]
